apiVersion: apps/v1
kind: Deployment
metadata:
  name: newcalci-deployment
  labels:
    app: newcalci
spec:
  replicas: 3
  selector:
    matchLabels:
      app: newcalci
  template:
    metadata:
      labels:
        app: newcalci
    spec:
      containers:
      - name: newcalci-container
        image: shantidocker123/calci
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: newcalci-service
spec:
  selector:
    app: newcalci
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
